using Microsoft.EntityFrameworkCore;
namespace BureauSync.Api;
public static class Roles { public const string Admin="BureauAdmin"; public const string Operator="BureauOperator"; public const string Submitter="LenderSubmitter"; }
public class User { public Guid Id {get;set;}=Guid.NewGuid(); public string Email {get;set;}=""; public string PasswordHash {get;set;}=""; public string Role {get;set;}=Roles.Operator; public bool IsActive {get;set;}=true; }
public class Lender { public Guid Id {get;set;}=Guid.NewGuid(); public string Code {get;set;}=""; public string Name {get;set;}=""; public bool IsActive {get;set;}=true; public string? SwiftBic {get;set;} public string? CbnLicense {get;set;} public string? Lei {get;set;} public string? CustomId {get;set;} }
public class Submission { public Guid Id {get;set;}=Guid.NewGuid(); public Guid LenderId {get;set;} public string FileName {get;set;}=""; public string FileHash {get;set;}=""; public string State {get;set;}="AwaitingReview"; public int Total {get;set;} public int Ready {get;set;} public int Review {get;set;} public int Rejected {get;set;} public DateTimeOffset SubmittedAt {get;set;}=DateTimeOffset.UtcNow; public List<SubmissionRecord> Records {get;set;}=[]; }
public class SubmissionRecord { public Guid Id {get;set;}=Guid.NewGuid(); public Guid SubmissionId {get;set;} public int RowNumber {get;set;} public string LenderCode {get;set;}=""; public string BorrowerName {get;set;}=""; public string IdentityId {get;set;}=""; public string AccountNumber {get;set;}=""; public decimal? LoanAmount {get;set;} public decimal? OutstandingBalance {get;set;} public string LoanStatus {get;set;}=""; public string Outcome {get;set;}="Ready"; public List<ValidationIssue> Issues {get;set;}=[]; }
public class ValidationIssue { public Guid Id {get;set;}=Guid.NewGuid(); public Guid SubmissionRecordId {get;set;} public string RuleCode {get;set;}=""; public string Field {get;set;}=""; public string Severity {get;set;}="Error"; public string Message {get;set;}=""; public string SuggestedAction {get;set;}=""; }
public class AuditEvent { public Guid Id {get;set;}=Guid.NewGuid(); public DateTimeOffset OccurredAt {get;set;}=DateTimeOffset.UtcNow; public Guid? ActorId {get;set;} public string Action {get;set;}=""; public string EntityType {get;set;}=""; public string EntityId {get;set;}=""; public string Detail {get;set;}=""; }
public class BureauSyncDb(DbContextOptions<BureauSyncDb> options):DbContext(options) { public DbSet<User> Users=>Set<User>();public DbSet<Lender> Lenders=>Set<Lender>();public DbSet<Submission> Submissions=>Set<Submission>();public DbSet<SubmissionRecord> SubmissionRecords=>Set<SubmissionRecord>();public DbSet<ValidationIssue> ValidationIssues=>Set<ValidationIssue>();public DbSet<AuditEvent> AuditEvents=>Set<AuditEvent>();protected override void OnModelCreating(ModelBuilder b){b.Entity<User>().HasIndex(x=>x.Email).IsUnique();b.Entity<Lender>().HasIndex(x=>x.Code).IsUnique();b.Entity<SubmissionRecord>().Property(x=>x.LoanAmount).HasPrecision(18,2);b.Entity<SubmissionRecord>().Property(x=>x.OutstandingBalance).HasPrecision(18,2);b.Entity<Submission>().HasMany(x=>x.Records).WithOne().HasForeignKey(x=>x.SubmissionId).OnDelete(DeleteBehavior.Cascade);b.Entity<SubmissionRecord>().HasMany(x=>x.Issues).WithOne().HasForeignKey(x=>x.SubmissionRecordId).OnDelete(DeleteBehavior.Cascade);} }
